# Generated by Django 4.2.1 on 2023-10-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
