# Generated by Django 4.2.1 on 2023-10-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cartitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
