# Generated by Django 4.2.1 on 2023-10-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
